### ISSUE TITLE
Rules & Highscore request for current season fails

### ISSUE THREAD

**Issue by H4zze** [Etimo/diamonds2#242] opened 2022-05-16 07:56 UTC
Requesting rules and highscore for the current season when swapping current board return HTTP 500 due to the selected board being undefined.

![image](https://user-images.githubusercontent.com/21332068/168545739-a3875342-d496-42a8-9f2f-d646526517d3.png)

**Comment by indrif** [comment] 2023-09-23 08:37
Don't know if still relevant for new frontend but please verify and close this otherwise

**Comment by wadholm** [comment] 2023-09-26 08:16
I can't reproduce this issue, it might not have been relevant for the new frontend. 
Closing issue.

**Comment by wadholm** [comment] 2023-09-26 08:18
I can't reproduce this issue, it might not have been relevant for the new frontend.
Closing issue.

**Comment by wadholm** [comment] 2023-09-26 10:10
Error displayed in the Games view.

**Closed** 2023-10-03 11:50 UTC
